name: Push main to another repository

on:
  push:
    branches:
      - main  # Trigger on changes to the 'main' branch

jobs:
  push-to-other-repo:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image for the runner
    steps:
      # Step 1: Checkout the source repository
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Full history to ensure that we can push to the destination repo

      # Step 2: Push to the destination repository
      - name: Push to destination repository
        env:
          API_TOKEN_GITHUB: ${{ secrets.DESTINATION_REPO_PAT }}
        run: |
          # Configure Git with a default user
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Clone the destination repository
          git clone https://${API_TOKEN_GITHUB}@github.com/lahiruthpala/E-Votie_FrontEnd.git E_votie_Vercel

          # Remove all files in the destination repository (except .git)
          find RecruitEase_Vercel -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +

          # Copy all files from the source to the destination repository
          rsync -av --exclude='.git' --exclude='.github' --exclude='E_votie_Vercel' ./ E_votie_Vercel/

          # Commit and push changes to the destination repository
          cd RecruitEase_Vercel
          git add .
          git commit -m "Update from source repository"
          git push origin main --force
